name: Build
on: [ push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 16
    name: Node ${{ matrix.node_version }} on ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Reason
        run: "echo ref: ${{github.ref}} event: ${{github.event_name}}"
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: NPM install with caching
        uses: bahmutov/npm-install@v1
      - name: Build Version
        run: |
          npm install --global replace-in-files-cli
          dotnet tool install --global minver-cli --version 2.5.0
          echo $(minver --tag-prefix v) >> $version
          echo "MINVERVERSIONOVERRIDE=$version" >> $GITHUB_ENV
          npm run version -- $version
          replace-in-files --regex='\/(v?((\d+)\.(\d+)(\.(\d+))?)(?:-([\dA-Za-z-]+(?:\.[\dA-Za-z-]+)*))?(?:\+([\dA-Za-z-]+(?:\.[\dA-Za-z-]+)*))?)' --replacement=/$version packages/core/src/configuration/Configuration.ts
      - name: Build
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Run Tests
        run: npm test
      - name: Push CI Packages
        if: github.event_name != 'pull_request' && matrix.os == 'ubuntu-latest'
        run: |
          echo @exceptionless:registry=https://npm.pkg.github.com >> .npmrc
          npm publish --workspaces --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Publish Release Packages
        if: startsWith(github.ref, 'refs/tags/v') && matrix.os == 'ubuntu-latest'
        run: npm publish --workspaces --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
