name: Build OSX
on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build Reason
        run: "echo ref: ${{github.ref}} event: ${{github.event_name}}"
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
      - name: NPM install with caching
        uses: bahmutov/npm-install@v1.1.0
      - name: Build
        run: gulp build
      - name: Run Tests
        run: gulp test
